
title: Carpentry@Oslo Study Group
description: "Study group for the Carpentries community at University of Oslo."
headlineSmall: "Welcome to Oslo Carpentry Study Group!"
headlineMain: "Let's Meet and Work Together"
avatar: "img/uio-carpentry-logo-small.png"

# ===============================
# Categories for sorting lessons.
# ===============================

languages:
  - python
  - r
  - git
  - misc

levels:
  - beginner
  - intermediate
  - advanced
