baseURL = "https://teebusch.github.io/uio-carpentry.github.io/"
languageCode = "en-us"
title = "Carpentry at the University of Oslo"

ignoreFiles = ["README.md"]

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

  [[module.imports]]
    path = "github.com/uio-carpentry/organisational"

    [[module.imports.mounts]]
        source = "reporting"
        target = "content/pages/reports"  

  [[module.imports]]
    path = "github.com/uio-carpentry/governance"

      [[module.imports.mounts]]
        source = "intro.rst"
        target = "content/pages/governance/intro.rst"

      [[module.imports.mounts]]
        source = "charter.rst"
        target = "content/pages/governance/charter.rst"

      [[module.imports.mounts]]
        source = "img/uio-carpentry-logo-circle.png"
        target = "content/pages/governance/img/uio-carpentry-logo-circle.png"

[params]
  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo = 'uio-carpentry-logo.png'

  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = 'pages'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/uio-carpentry/uio-carpentry.github.io'

  # Enable 'Edit this page' links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to the site directory.
  BookEditPath = '/'

  # (Optional, default true) Enables comments template on pages
  # By default partials/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments = false