name: deploy to gihub pages

on:
  push:
    branches:
      - main
      - master
      - use_hugo  # development only

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          submodules: true
          fetch-depth: 0
          
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Setup Python
      uses: "actions/setup-python@v2"

    - name: Install rst2html
      run: pip install rst2html

    - name: Build Site
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true  